### ISSUE TITLE
Doesn't work with first publish with scope

### ISSUE THREAD

**Issue by ecmadao** [ljharb/safe-publish-latest#10]
If I publish with a scope, for example, using:

```json
{
  "name": "@ecmadao/my-project"
}
```

safe-publish-latest looking up the versions fails, which kills the publish.

For more 404 error message difference between `package-name` and `@scope/package-name`, you can see the following screenshot:

![](http://obpykithy.bkt.clouddn.com/ecmadao/npm-pubilsh.png)

And I have already create a PR. By the way, thanks for your package!

**Comment by ljharb** [comment]
Fixed in e04d9b3347334c226f5784fee3efa71b85311c1c

**Comment by ecmadao** [comment]
@ljharb 
Cool. Thank you.
